"""Generates tokens.ts and tokens.json from tokens.css (the source of truth).

Run from anywhere:  python docs/design/brand-kit/build-tokens.py
Only the light :root block is exported; dark values live in tokens.css (and globals.css).
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).parent
css = (HERE / "tokens.css").read_text(encoding="utf-8")
light = css.split(':root[data-theme="dark"]')[0]
dark = css.split(':root[data-theme="dark"]')[1]

def parse(block: str) -> dict[str, str]:
    return {m[0]: m[1].strip() for m in re.findall(r"--tf-([\w-]+):\s*([^;]+);", block)}

L, D = parse(light), parse(dark)

GROUPS = {
    "color": ["ink", "primary", "text", "muted", "subtle", "disabled", "page", "surface", "selected", "canvas",
              "field", "line", "line-soft", "overlay", "success", "success-soft", "danger", "danger-soft", "info",
              "toast-bg", "toast-line", "badge-bg", "badge-line", "badge-text"],
    "questionType": ["qt-text", "qt-choice", "qt-rating", "qt-contact", "qt-other", "qt-screen"],
    "formTheme": ["form-bg", "form-text", "form-button"],
    "fontSize": ["text-xs", "text-sm", "text-base", "text-md", "text-lg", "text-xl", "text-q", "text-answer"],
    "spacing": [k for k in L if k.startswith("space-")],
    "radius": [k for k in L if k.startswith("radius-")],
    "shadow": [k for k in L if k.startswith("shadow-")],
    "easing": [k for k in L if k.startswith("ease-")],
    "duration": [k for k in L if k.startswith("dur-")],
}
DTCG_TYPE = {"color": "color", "questionType": "color", "formTheme": "color", "fontSize": "dimension",
             "spacing": "dimension", "radius": "dimension", "shadow": "shadow", "easing": "cubicBezier",
             "duration": "duration"}

def camel(name: str, prefix: str = "") -> str:
    name = name.removeprefix(prefix)
    head, *rest = name.split("-")
    return head + "".join(p.capitalize() for p in rest)

PREFIX = {"questionType": "qt-", "formTheme": "form-", "fontSize": "text-", "spacing": "space-", "radius": "radius-",
          "shadow": "shadow-", "easing": "ease-", "duration": "dur-"}

tokens = {g: {camel(k, PREFIX.get(g, "")): L[k] for k in keys} for g, keys in GROUPS.items()}
tokens["darkColor"] = {camel(k, ""): v for k, v in D.items()}
tokens["font"] = {"family": L["font"]}

# ---- tokens.json (DTCG) ----
dtcg: dict = {"$description": "Typeform Original design tokens v1.0 (generated from tokens.css)"}
for group, values in tokens.items():
    if group == "font":
        dtcg["font"] = {"family": {"$type": "fontFamily", "$value": values["family"]}}
        continue
    kind = DTCG_TYPE.get(group, "color")
    dtcg[group] = {}
    for name, value in values.items():
        if kind == "cubicBezier":
            value = [float(x) for x in re.findall(r"[\d.]+", value)]
        dtcg[group][name] = {"$type": kind, "$value": value}
(HERE / "tokens.json").write_text(json.dumps(dtcg, indent=2) + "\n", encoding="utf-8")

# ---- tokens.ts ----
lines = ["// Typeform Original design tokens v1.0. Generated by build-tokens.py from tokens.css: do not edit by hand.", ""]
for group, values in tokens.items():
    lines.append(f"export const {group} = {json.dumps(values, indent=2)} as const;")
    lines.append("")
lines.append("export const theme = {")
lines.append('  name: "Typeform Original",')
lines.append('  version: "1.0.0",')
for group in tokens:
    lines.append(f"  {group},")
lines.append("} as const;")
lines.append("")
lines.append("export default theme;")
(HERE / "tokens.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote tokens.json + tokens.ts ({sum(len(v) for v in tokens.values())} tokens)")
