// Typeform Original design tokens v1.0. Generated by build-tokens.py from tokens.css: do not edit by hand.

export const color = {
  "ink": "#2a222b",
  "primary": "#3c323e",
  "text": "#4c414e",
  "muted": "#655d67",
  "subtle": "#847e85",
  "disabled": "#c4c1c5",
  "page": "#ffffff",
  "surface": "#f7f7f8",
  "selected": "#ededee",
  "canvas": "#fafafa",
  "field": "#fdfdfe",
  "line": "#e4e3e5",
  "lineSoft": "#ebeaec",
  "overlay": "rgb(42 34 43 / 0.7)",
  "success": "#177767",
  "successSoft": "#f4faf8",
  "danger": "#c0392b",
  "dangerSoft": "#fdeceb",
  "info": "#2f7bd3",
  "toastBg": "#fafcff",
  "toastLine": "#9ac9f4",
  "badgeBg": "#f6fafd",
  "badgeLine": "#bdddf9",
  "badgeText": "#01487f"
} as const;

export const questionType = {
  "text": "#bdddf9",
  "choice": "#ddd6fa",
  "rating": "#c4e3ba",
  "contact": "#f8cdd8",
  "other": "#fbe19d",
  "screen": "#dedcde"
} as const;

export const formTheme = {
  "bg": "#fafafa",
  "text": "#2a222b",
  "button": "#2a222b"
} as const;

export const fontSize = {
  "xs": "12px",
  "sm": "13px",
  "base": "14px",
  "md": "16px",
  "lg": "20px",
  "xl": "24px",
  "q": "26px",
  "answer": "30px"
} as const;

export const spacing = {
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "5": "20px",
  "6": "24px",
  "8": "32px",
  "10": "40px",
  "12": "48px"
} as const;

export const radius = {
  "sm": "6px",
  "md": "8px",
  "row": "10px",
  "lg": "12px",
  "modal": "16px",
  "pill": "999px"
} as const;

export const shadow = {
  "row": "0 1px 4px rgb(42 34 43 / 0.06)",
  "popover": "0 4px 16px rgb(42 34 43 / 0.12), 0 1px 3px rgb(42 34 43 / 0.08)",
  "modal": "0 16px 48px rgb(42 34 43 / 0.2)",
  "toast": "0 4px 16px rgb(42 34 43 / 0.08)"
} as const;

export const easing = {
  "out": "cubic-bezier(0.23, 1, 0.32, 1)",
  "inOut": "cubic-bezier(0.77, 0, 0.175, 1)",
  "drawer": "cubic-bezier(0.32, 0.72, 0, 1)"
} as const;

export const duration = {
  "press": "120ms",
  "hover": "150ms",
  "menu": "180ms",
  "modal": "240ms",
  "questionIn": "350ms",
  "questionOut": "250ms"
} as const;

export const darkColor = {
  "ink": "#ffffff",
  "primary": "#f3f0f3",
  "text": "#e2dde3",
  "muted": "#b4adb5",
  "subtle": "#918a92",
  "disabled": "#5a535b",
  "page": "#262128",
  "surface": "#1a171b",
  "selected": "#353037",
  "canvas": "#201c21",
  "field": "#2b262d",
  "line": "#423b44",
  "lineSoft": "#322c34",
  "overlay": "rgb(0 0 0 / 0.6)",
  "success": "#5ccb94",
  "successSoft": "#173323",
  "danger": "#f2716a",
  "dangerSoft": "#3b1f1d",
  "toastBg": "#1f2633",
  "toastLine": "#34557f",
  "badgeBg": "#1c2633",
  "badgeLine": "#34557f",
  "badgeText": "#9fc4f5",
  "qtText": "#8fc3f3",
  "qtChoice": "#b6a8f4",
  "qtRating": "#9ed58b",
  "qtContact": "#f2a2b9",
  "qtOther": "#f4cd6c",
  "qtScreen": "#bab4bd"
} as const;

export const font = {
  "family": "\"Inter\", system-ui, sans-serif"
} as const;

export const theme = {
  name: "Typeform Original",
  version: "1.0.0",
  color,
  questionType,
  formTheme,
  fontSize,
  spacing,
  radius,
  shadow,
  easing,
  duration,
  darkColor,
  font,
} as const;

export default theme;
